### ISSUE TITLE
Sample files should be included in freeeed processing

### ISSUE THREAD

**Issue by hnviradiya** [shmsoft/FreeEed#199]
It gives file not found when running freeeed processing. IMHO it should be included in git.

Exception in thread "main" java.lang.IllegalStateException: file not found issue issue: E:\FreeEed\freeeed-processing\samples\13.eml
	at org.freeeed.mail.EmlParser.parseEmail(EmlParser.java:106)
	at org.freeeed.mail.EmlParser.<init>(EmlParser.java:77)
	at org.freeeed.mail.EmlParser.main(EmlParser.java:282)

**Comment by markkerzner** [comment]
this may be related to the way you run it, not to the actual fils

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
LinkedIn <https://www.linkedin.com/in/markkerzner/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale <https://twitter.com/elephantscale>
