### ISSUE TITLE
After processing, created zip file is not opening

### ISSUE THREAD

**Issue by hnviradiya** [shmsoft/FreeEed#201]
Hello sir,

I processed data locally. It creates zip file, but it seems to be corrupted.

Size is shown as 0kb. (if I install winzip, then it shows proper size), and if I click on it, it will not open stating that permission denied (in winzip, it says something like file is not in proper format)

In Processing history, it says that processing done.

I am using windows 10 64bit. 

Running this project through netbeans
steps I have performed
1) build with dependencies parent project 
2) debug freeeed-ui 
3) select project from freeeed-ui
4) run locally from freeeed-ui

Installed Java version 1.8

**Comment by markkerzner** [comment]
http://freeeed.org/index.php/support

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
LinkedIn <https://www.linkedin.com/in/markkerzner/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale <https://twitter.com/elephantscale>

**Comment by sadev5264** [comment]
when trying to build the project getting below error : 

`Failed to execute goal on project freeeed-processing: Could not resolve dependencies for project org.freeeed:freeeed-processing:jar:1.0-SNAPSHOT: Failure to find com.ibm:notes:jar:1.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`

**Comment by sadev5264** [comment]
Getting below error when processing locally`ERROR [org.freeeed.search.files.CaseFileService] Problem unpacking: C:\Users\sutha\Downloads\freeeed_complete_pack-7.7.4\FreeEed\output\freeeed-output\1\output\results\native.zip
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.freeeed.search.files.ZipUtil.unzipFile(ZipUtil.java:112)
        at org.freeeed.search.files.CaseFileService.expandCaseFiles(CaseFileService.java:66)
        at org.freeeed.search.web.controller.cases.CaseController.execute(CaseController.java:145)
        at org.freeeed.search.web.controller.commons.BaseController.handleRequest(BaseController.java:72)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
`
