### ISSUE TITLE
JAI Image I/O Package

### ISSUE THREAD

**Issue by n3tl0kr** [shmsoft/FreeEed#230]
Hi everyone!

I'm using FreeEed for the first time and running into a couple of issues on both MacOS and Windows10.  

`3858988 [pool-1-thread-37914] ERROR net.sourceforge.tess4j.Tesseract  - Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://github.com/jai-imageio/jai-imageio-core
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:215)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:195)
	at org.freeeed.ocr.PdfTextParser.parseImages(PdfTextParser.java:79)
	at org.freeeed.ocr.PdfTextParser.parseContent(PdfTextParser.java:58)
	at org.freeeed.main.DocumentParser.parse(DocumentParser.java:81)
	at org.freeeed.main.FileProcessor.extractMetadata(FileProcessor.java:225)
	at org.freeeed.main.FileProcessor.run(FileProcessor.java:278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

I've pulled this jar file but i'm not 100% sure how to integrate it into the associated binary?  Any ideas?

**Comment by farshidmh** [comment]
Hello,

Which OS is giving you this error?
and can you please check your java version?  ( in terminal => java -v)

**Comment by markkerzner** [comment]
No response, no detail, closing
