### ISSUE TITLE
ERROR org.freeeed.data.index.ESIndex - java.lang.NullPointerException

### ISSUE THREAD

**Issue by velinbudinov** [shmsoft/FreeEed#231]
Hello there,

I've some issues when creating case:

OS: Ubuntu 18.04
java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

find /DIR_to_index/ -type f | wc -l
53800

log:
2020-06-07 11:13:04 177610 [pool-2-thread-64] DEBUG org.freeeed.mail.EmlParser  - Adding attachment: Uslovie.doc
2020-06-07 11:13:04 177613 [pool-2-thread-14] DEBUG org.freeeed.mail.EmlParser  - Adding attachment: null
2020-06-07 11:13:04 177645 [pool-1-thread-1] ERROR org.apache.http.impl.nio.client.InternalHttpAsyncClient  - I/O reactor terminated abnormally
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:356)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:606)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:629)
        at org.elasticsearch.client.RestClient$1.failed(RestClient.java:400)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:155)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:276)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        ... 1 more
2020-06-07 11:13:04 177648 [pool-2-thread-31] ERROR org.freeeed.data.index.ESIndex  - java.lang.NullPointerException
2020-06-07 11:13:04 177651 [pool-2-thread-31] DEBUG org.freeeed.mail.EmlParser  - Adding attachment: image.pdf
2020-06-07 11:13:04 177657 [pool-2-thread-40] ERROR org.freeeed.data.index.ESIndex  - java.lang.NullPointerException
2020-06-07 11:13:04 177664 [pool-2-thread-11] ERROR org.freeeed.data.index.ESIndex  - java.lang.NullPointerException

Regards.
Velin

**Comment by markkerzner** [comment]
I got the data and will be fixing it

**Comment by markkerzner** [comment]
Working on it now, sorry it took exactly from June 7 till July 7

**Comment by markkerzner** [comment]
All works in 8.0.3
