### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by M-F-P** [shmsoft/FreeEed#346]
No matter how or where I use freeeed, I get this message when I attempt to process a .pst file. I have tried placing the project folder in various directories and used multiple different distros of Java, Oracle, Corretto & etc., and different versions (but always begin with version 8. Nothing works. I have triple confirmed my environment variables are correct. This is on windows.

The following is the error message from the logs I get ever time I try to process the .pst file.:

```
2023-02-07 19:00:32 1    [AWT-EventQueue-0] INFO  org.freeeed.ui.FreeEedUI  - System check:
2023-02-07 19:00:32 9    [AWT-EventQueue-0] INFO  org.freeeed.ui.FreeEedUI  - readpst (PST extraction): false
2023-02-07 19:00:32 10   [AWT-EventQueue-0] INFO  org.freeeed.ui.FreeEedUI  - wkhtmltopdf (html to pdf printing): false
2023-02-07 19:00:32 10   [AWT-EventQueue-0] INFO  org.freeeed.ui.FreeEedUI  - soffice (LibreOffice command line interface): false
2023-02-07 19:00:32 137  [AWT-EventQueue-0] DEBUG org.freeeed.db.DbLocal  - Table mode exists? - false
2023-02-07 19:00:32 156  [AWT-EventQueue-0] DEBUG org.freeeed.db.DbLocal  - Table settings exists? - false
2023-02-07 19:00:33 954  [AWT-EventQueue-0] INFO  org.freeeed.services.Services  - Starting services
2023-02-07 19:00:43 11901 [AWT-EventQueue-0] DEBUG org.freeeed.db.DbLocal  - Table project exists? - false
2023-02-07 19:00:46 14780 [AWT-EventQueue-0] DEBUG org.freeeed.ui.ProjectsUI  - Opening project 2
2023-02-07 19:01:59 87055 [Thread-3] INFO  org.freeeed.main.ActionStaging  - Staging project: 2/FreeEed sample project
2023-02-07 19:01:59 87058 [Thread-3] INFO  org.freeeed.main.ActionStaging  - Packaging and staging the following directories for processing:
2023-02-07 19:01:59 87059 [Thread-3] INFO  org.freeeed.main.PackageArchive  - Writing output to staging: output\freeeed-output\2\output\staging\input00001.zip
2023-02-07 19:01:59 87059 [Thread-3] INFO  org.freeeed.main.ActionStaging  - C:\Users\jg\Desktop\email\HDD\working_copy_220207\
2023-02-07 19:02:13 101462 [Thread-3] INFO  org.freeeed.main.PackageArchive  - Wrote 1 files
2023-02-07 19:02:13 101469 [Thread-3] INFO  org.freeeed.main.PackageArchive  - Writing output to staging: output\freeeed-output\2\output\staging\input00002.zip
2023-02-07 19:02:13 101469 [Thread-3] INFO  org.freeeed.main.ActionStaging  - Done staging
2023-02-07 19:02:27 115145 [Thread-4] INFO  org.freeeed.main.ActionProcessing  - Processing project: FreeEed sample project
2023-02-07 19:02:27 115152 [Thread-4] DEBUG org.freeeed.data.index.SolrIndex  - SolrIndex Create HttpSolrIndex
2023-02-07 19:02:28 115972 [Thread-4] DEBUG org.freeeed.db.DbLocal  - Table metadata exists? - false
2023-02-07 19:02:28 116116 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: UPI  164859575
2023-02-07 19:02:28 116116 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: File Name  164859575
2023-02-07 19:02:28 116117 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Custodian  164859575
2023-02-07 19:02:28 116117 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Source Device  164859575
2023-02-07 19:02:28 116117 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Source Path  164859575
2023-02-07 19:02:28 116117 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Production Path  164859575
2023-02-07 19:02:28 116118 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Modified Date  164859575
2023-02-07 19:02:28 116118 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Modified Time  164859575
2023-02-07 19:02:28 116118 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Time Offset Value  164859575
2023-02-07 19:02:28 116118 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: processing_exception  164859575
2023-02-07 19:02:28 116119 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: master_duplicate  164859575
2023-02-07 19:02:28 116119 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: text  164859575
2023-02-07 19:02:28 116119 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Creation Date  164859575
2023-02-07 19:02:28 116119 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: To  164859575
2023-02-07 19:02:28 116120 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: From  164859575
2023-02-07 19:02:28 116120 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: CC  164859575
2023-02-07 19:02:28 116120 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: BCC  164859575
2023-02-07 19:02:28 116120 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Date Sent  164859575
2023-02-07 19:02:28 116121 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Time Sent  164859575
2023-02-07 19:02:28 116121 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Subject  164859575
2023-02-07 19:02:28 116121 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Date Received  164859575
2023-02-07 19:02:28 116124 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Time Received  164859575
2023-02-07 19:02:28 116124 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: native_link  164859575
2023-02-07 19:02:28 116124 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: text_link  164859575
2023-02-07 19:02:28 116125 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: exception_link  164859575
2023-02-07 19:02:28 116125 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: attachment_parent  164859575
2023-02-07 19:02:28 116125 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: message_id  164859575
2023-02-07 19:02:28 116125 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: references  164859575
2023-02-07 19:02:28 116125 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: File Type  164859575
2023-02-07 19:02:28 116126 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: Hash  164859575
2023-02-07 19:02:28 116126 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: extracted_pii  164859575
2023-02-07 19:02:28 116126 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - CREATED new header: summary  164859575
2023-02-07 19:02:28 116127 [Thread-4] DEBUG org.freeeed.mr.MetadataWriter  - Filename: output\freeeed-output\2\output\results\metadata1.csv
2023-02-07 19:02:28 116129 [Thread-4] INFO  org.freeeed.metadata.ColumnMetadata  - 164859575 > HEADERS: UPI|File Name|Custodian|Source Device|Source Path|Production Path|Modified Date|Modified Time|Time Offset Value|processing_exception|master_duplicate|text|Creation Date|To|From|CC|BCC|Date Sent|Time Sent|Subject|Date Received|Time Received|native_link|text_link|exception_link|attachment_parent|message_id|references|File Type|Hash|extracted_pii|summary
2023-02-07 19:02:28 116130 [Thread-4] DEBUG org.freeeed.main.ZipFileWriter  - Filename: output\freeeed-output\2\output\results\native1.zip, Root dir: output\freeeed-output\2\output\results
2023-02-07 19:02:28 116136 [Thread-4] ERROR org.freeeed.main.ActionProcessing  - Running action processing
java.lang.IllegalStateException: 1
	at org.freeeed.main.ActionProcessing.process(ActionProcessing.java:87)
	at org.freeeed.main.ActionProcessing.run(ActionProcessing.java:55)
	at java.lang.Thread.run(Thread.java:750)
```

I have used both the zip file that is downloaded from the link from the HOWTO and the zip file from the demo page. Same result from both.

**Comment by markkerzner** [comment]
This line tells me that PST extractor is not installed.

2023-02-07 19:00:32 9    [AWT-EventQueue-0] INFO
org.freeeed.ui.FreeEedUI  - readpst (PST extraction): false


Can you try it on Ubuntu?

Mark Kerzner, President, Elephant Scale
<https://t.sidekickopen60.com/s3t/c/5/f18dQhb0V1-gmb8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj26QkH1W3ZVd9v3zd-ghW3F4Fph1JxwY51V3&si=8000000003820840&pi=f8a2293c-d2bf-4ae8-993e-95e2c0d8dc18>
,
713-724-2534 Book a call with me
<https://t.sidekickopen60.com/s3t/c/5/f18dQhb0V1-gmb8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj4cm2zwW3P4yD541QtgsW4hCPvh43T4P1W3zgDm_3K8RJW3b2k2&si=8000000003820840&pi=f8a2293c-d2bf-4ae8-993e-95e2c0d8dc18>

**Comment by markkerzner** [comment]
I am working on V10 which will be more polished.

Mark Kerzner, President, Elephant Scale
<https://t.sidekickopen60.com/s3t/c/5/f18dQhb0V1-gmb8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj26QkH1W3ZVd9v3zd-ghW3F4Fph1JxwY51V3&si=8000000003820840&pi=39ca193a-70e9-4651-9a91-58c74c4ca75b>
,
713-724-2534 Book a call with me
<https://t.sidekickopen60.com/s3t/c/5/f18dQhb0V1-gmb8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj4cm2zwW3P4yD541QtgsW4hCPvh43T4P1W3zgDm_3K8RJW3b2k2&si=8000000003820840&pi=39ca193a-70e9-4651-9a91-58c74c4ca75b>

**Comment by markkerzner** [comment]
Thank you. You will have to wait for the new release.

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
713-724-2534 Book a call with me <https://go.oncehub.com/markkerzner>

**Comment by Controller5** [comment]
Ciao all, 

Sorry I know this is a bit old here, but I was having a very similar issue when trying to use FreeEed: the demo docs were working, but mine weren't. I went back to look at the different between the demo docs and in the project options for my project the "Custodian" column was empty. This field is editable, and I added "c1" to the field. This fixed the issue, so I think this is a bit of a bug. Unfortunately because you can't add to the Custodian column in mass, it means you would have to manually add something to this field to make FreeEed usable. 

Mr. Kerzner, perhaps you have a solution, or this is by design and there is something I am missing here.

Images:

<img width="861" alt="Screen Shot 2023-12-05 at 9 43 55 AM" src="https://github.com/shmsoft/FreeEed/assets/128665800/3c82d7c5-e0aa-4a16-81f1-659263e7fc71">
<img width="824" alt="Screen Shot 2023-12-05 at 9 43 41 AM" src="https://github.com/shmsoft/FreeEed/assets/128665800/1a74582d-1c9e-46b2-a1a7-61b18286e60a">

**Comment by markkerzner** [comment]
Hi,

Make sure you have the latest version. Currently, it is 10.0.9.

Also, I recommend getting support, which you need for many reasons:
https://freeeed.org/support/
Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
Book a call with me <https://go.oncehub.com/markkerzner> 713-724-2534
