### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by PaulP-iom** [shmsoft/FreeEed#353]
i've staged a dataset and when i try to proxcess locally i get the following

Exception in thread "Thread-2" java.lang.OutOfMemoryError: file is too large to fit in a byte array: 7389839360 bytes
        at com.google.common.io.Files.readFile(Files.java:174)
        at com.google.common.io.Files$FileByteSource.read(Files.java:151)
        at com.google.common.io.Files.toByteArray(Files.java:260)
        at org.freeeed.services.Util.getFileContent(Util.java:41)
        at org.freeeed.main.FileProcessor.createMapWritable(FileProcessor.java:316)
        at org.freeeed.main.FileProcessor.writeMetadata(FileProcessor.java:296)
        at org.freeeed.main.FileProcessor.processFileEntry(FileProcessor.java:236)
        at org.freeeed.main.ZipFileProcessor.processArchivesRecursively(ZipFileProcessor.java:205)
        at org.freeeed.main.ZipFileProcessor.processArchivesRecursively(ZipFileProcessor.java:178)
        at org.freeeed.main.ZipFileProcessor.processArchivesRecursively(ZipFileProcessor.java:178)
        at org.freeeed.main.ZipFileProcessor.processArchivesRecursively(ZipFileProcessor.java:178)
        at org.freeeed.main.ZipFileProcessor.processWithTrueZip(ZipFileProcessor.java:155)
        at org.freeeed.main.ZipFileProcessor.process(ZipFileProcessor.java:95)
        at org.freeeed.main.MainRunner.run(MainRunner.java:63)
        at org.freeeed.mr.FreeEedMR.main(FreeEedMR.java:154)
        at org.freeeed.main.ActionProcessing.process(ActionProcessing.java:84)
        at org.freeeed.main.ActionProcessing.run(ActionProcessing.java:55)
        at java.lang.Thread.run(Unknown Source)

i have installed 64 bit java and modified the startup batch file as shown (increased xms to 1024/1536 and xmx to 8gb/10gb)

 java -Xms2048m -Xmx12288m -Dlog4j.configuration=file:"config/log4j.properties" -cp target/freeeed-processing-1.0-SNAPSHOT-jar-with-dependencies.jar;drivers/truezip-driver-zip-7.3.4.jar org.freeeed.ui.FreeEedUI

any ideas where i can go next

cheers

Paul

**Comment by markkerzner** [comment]
Paul, 

Who are you, what happened, and do you have support?

Thank you,
Mark
